# -*- coding: utf-8 -*-
"""Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsE4dKLjlBCwHgENTCzGHWnZ4t_QD773

# Trabajo Práctico Integrador: Clasificador de Residuos Urbanos
## Contexto del Problema y Marco Legal (GIRSU Mendoza)

La gestión eficiente de los Residuos Sólidos Urbanos (RSU) representa uno de los desafíos ambientales más críticos de la provincia de Mendoza. En consonancia con la **Ley Provincial 5.961** de preservación del medio ambiente y los lineamientos de la **Gestión Integral de Residuos Sólidos Urbanos (GIRSU)**, la separación en origen es el pilar fundamental para reducir el volumen de rechazo que se destina a los centros de disposición final.

Para facilitar este proceso al ciudadano, este proyecto propone una solución automatizada mediante Redes Neuronales Profundas capaz de clasificar de manera inmediata el tipo de residuo a partir de una fotografía urbana estándar.

### Clasificación de Residuos Adoptada
A fin de asegurar la viabilidad e interoperabilidad de la aplicación con la normativa vigente en los municipios de la provincia, el dataset ha sido mapeado y consolidado en cuatro grandes contenedores destino:

*   **Contenedor VERDE (Secos Reciclables):** Cartón, vidrio, metales, papel y plásticos limpios.
*   **Contenedor NEGRO (Húmedos / Rechazo):** Residuos biológicos, restos de comida y basura no recuperable.
*   **Contenedor AMARILLO (Pilas y RAEE):** Baterías, componentes electrónicos y residuos peligrosos de origen domiciliario.
*   **Contenedor MARRÓN (Textil y Calzado):** Ropa, telas y zapatos en desuso.

---
"""

import os
import zipfile
import shutil
# Import gdown for downloading files from Google Drive without mounting
!pip install gdown -q
import gdown

# 1. Eliminar el montaje de Google Drive y descargar el dataset directamente
#    El profesor solicitó no montar Drive y descargar desde un enlace público.
#    REEMPLAZA 'YOUR_PUBLIC_GOOGLE_DRIVE_ID_HERE' CON EL ID DE TU ARCHIVO ZIP PÚBLICO.
#    Puedes obtener el ID de un archivo en Google Drive desde su URL de compartir.

# 2. Crear estructura del repositorio
os.makedirs("data/raw", exist_ok=True)
os.makedirs("dev", exist_ok=True)
os.makedirs("prod", exist_ok=True)

drive_file_id = '1pNlHIgPxUm0GoqhOUlLUy6Ow1-y1jfWx' # <--- CAMBIAR ESTO
local_zip_path = "Residuos_contenedores.zip"

try:
    print(f"Descargando el dataset desde Google Drive ID: {drive_file_id}...")
    gdown.download(id=drive_file_id, output=local_zip_path, quiet=False)
    print("✓ Archivo zip descargado correctamente.")

    print("Descomprimiendo el dataset...")
    with zipfile.ZipFile(local_zip_path, 'r') as zip_ref:
        # Ensure extraction path is data/raw, and it handles the internal folder structure
        zip_ref.extractall("data/raw")
    print("✓ Dataset descomprimido correctamente en data/raw/")
    os.remove(local_zip_path) # Limpiar el archivo zip descargado
except Exception as e:
    print(f"Error al descargar o descomprimir el archivo: {e}")
    print("Por favor, asegúrate de que el 'drive_file_id' sea correcto y que el archivo sea público.")

# 3. Crear el .gitignore reglamentario
gitignore_content = """
data/raw/
*.zip
*.jpg
*.jpeg
*.png
__pycache__/
.ipynb_checkpoints/
"""
with open(".gitignore", "w") as f:
    f.write(gitignore_content.strip())
print("✓ Archivo .gitignore configurado.")

"""Celda 2: Mapeo de Clases GIRSU Mendoza y Creación de Splits Estratificados (CSV)

**Nota del Profesor:** El dataset ya debe estar dividido por contenedores. Esto significa que las subcarpetas dentro de `data/raw/Residuos contenedores/` (o la carpeta raíz después de la descompresión) deben ser directamente los nombres de los contenedores (ej. "VERDE (Secos Reciclables)", "NEGRO (Húmedos / Rechazo)", etc.) y no las categorías individuales como 'cardboard' o 'glass'.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import glob
import os

# El profesor indicó que el dataset ya debe estar "dividido por contenedores".
# Esto significa que las carpetas dentro de `data/raw/...` serán los nombres de los contenedores.
# Por lo tanto, el MAPEO_GIRSU original (de categorías a contenedores) ya no es necesario si las carpetas ya son los contenedores.

CONTENEDORES_NAMES = {
    0: "VERDE (Secos reciclables)",
    1: "NEGRO (Humedos rechazo)",
    2: "AMARILLO (Electronicos rechazo parcial)",
    3: "MARRON (Textil especial)"
}

# Mapeo inverso de nombres de carpeta (contenedores) a labels numéricas
# Asumimos que los nombres de las carpetas coinciden exactamente con los VALORES de CONTENEDORES_NAMES
REVERSE_CONTENEDORES_NAMES = {v: k for k, v in CONTENEDORES_NAMES.items()}

# Buscar todas las imágenes en las subcarpetas de data/raw
extensiones = ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']
archivos_imagenes = []
for ext in extensiones:
    # La búsqueda recursiva '/**/*/' es importante si hay una carpeta intermedia como 'Residuos contenedores'
    archivos_imagenes.extend(glob.glob(f"data/raw/**/*/{ext}", recursive=True))

# Construir el DataFrame base con rutas relativas
data_rows = []
for filepath in archivos_imagenes:
    # Extraer el nombre de la carpeta padre, que ahora debería ser el nombre del contenedor
    container_folder_name = os.path.basename(os.path.dirname(filepath))

    if container_folder_name in REVERSE_CONTENEDORES_NAMES:
        label = REVERSE_CONTENEDORES_NAMES[container_folder_name]
        ruta_relativa = os.path.relpath(filepath, start=".")
        data_rows.append({"filepath": ruta_relativa, "label": label})
    else:
        # Si el nombre de la carpeta no se reconoce como un contenedor, imprimir una advertencia
        # Esto es útil para depurar si la estructura del dataset no es la esperada.
        print(f"Advertencia: Nombre de carpeta '{container_folder_name}' no reconocido como contenedor. Saltando {filepath}")

df_total = pd.DataFrame(data_rows)

# Verificar que el DataFrame no esté vacío antes de continuar
if df_total.empty:
    print("Error: No se encontraron imágenes válidas para los contenedores definidos. Por favor, revisa la estructura de tu dataset y los nombres de las carpetas.")
else:
    # Distribucion real
    print("Distribución total por Contenedor destino:")
    print(df_total['label'].value_counts().rename(index=CONTENEDORES_NAMES))

    # Particionado Estratificado Reproducible (Seed fija)
    SEED = 31
    train_df, val_test_df = train_test_split(
        df_total, test_size=0.30, random_state=SEED, stratify=df_total['label']
    )
    val_df, test_df = train_test_split(
        val_test_df, test_size=0.50, random_state=SEED, stratify=val_test_df['label']
    )

    # Guardar los CSV indexados livianos dentro de data/
    train_df.to_csv("data/train.csv", index=False)
    val_df.to_csv("data/val.csv", index=False)
    test_df.to_csv("data/test.csv", index=False)

    print(f"\nSplits generados con éxito (Seed: {SEED}):")
    print(f" - Train (70%): {len(train_df)} imágenes")
    print(f" - Validación (15%): {len(val_df)} imágenes")
    print(f" - Test (15%): {len(test_df)} imágenes")

"""Celda 3: Implementación de la Clase Dataset en PyTorch"""

import torch
from torch.utils.data import Dataset
from PIL import Image

class GarbageGIRSUDataset(Dataset):
    """Clase Dataset personalizada para la gestión de residuos bajo la Ley GIRSU Mendoza."""
    def __init__(self, csv_path, transform=None):
        self.data_frame = pd.read_csv(csv_path)
        self.transform = transform

    def __len__(self):
        return len(self.data_frame)

    def __getitem__(self, idx):
        img_path = self.data_frame.iloc[idx, 0]
        label = int(self.data_frame.iloc[idx, 1])

        # Carga robusta en modo RGB para mitigar problemas con imágenes en escala de grises
        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, label

"""Celda 4: Data Augmentation y Configuración de los DataLoaders"""

from torchvision import transforms
from torch.utils.data import DataLoader

IMG_SIZE = 224
BATCH_SIZE = 32

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# Pipeline de Entrenamiento con Data Augmentation para producción
train_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.3),
    transforms.RandomRotation(degrees=30),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

# Pipeline de Validación y Test (Sin aumentación)
val_test_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

# Instanciación
train_dataset = GarbageGIRSUDataset("data/train.csv", transform=train_transforms)
val_dataset   = GarbageGIRSUDataset("data/val.csv", transform=val_test_transforms)
test_dataset  = GarbageGIRSUDataset("data/test.csv", transform=val_test_transforms)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)
val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print("DataLoaders configurados correctamente de forma independiente.")

"""Celda 5: Verificación Visual del Efecto de las Augmentations"""

import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
import numpy as np

# La función ahora toma el dataset ya creado y el pipeline de transformaciones
def mostrar_aumentaciones(dataset, transform_pipeline, num_imagenes=4, num_variaciones=3):
    """Muestra el efecto de data augmentation en varias imágenes del dataset.

    Args:
        dataset (torch.utils.data.Dataset): El dataset (ej. train_dataset) con imágenes y labels.
        transform_pipeline (torchvision.transforms.Compose): El pipeline de transformaciones a aplicar.
        num_imagenes (int): Número de imágenes distintas a mostrar.
        num_variaciones (int): Número de versiones aumentadas para cada imagen.
    """
    # Creamos una grilla: filas = imágenes distintas, columnas = variaciones de cada una
    fig, axs = plt.subplots(num_imagenes, num_variaciones, figsize=(15, 3 * num_imagenes))
    fig.suptitle("Data Augmentation: Versiones Aumentadas de Imágenes Distintas", fontsize=14, fontweight='bold')

    for row in range(num_imagenes):
        # Obtener la ruta de la imagen original del dataframe subyacente del dataset
        # Usamos .data_frame para acceder al pandas DataFrame dentro de GarbageGIRSUDataset
        img_path = dataset.data_frame.iloc[row, 0]
        raw_image = Image.open(img_path).convert("RGB")

        for col in range(num_variaciones):
            # Aplicamos el pipeline de transformaciones directamente a la imagen RAW
            # para generar múltiples aumentaciones de la MISMA imagen original.
            tensor_img = transform_pipeline(raw_image)

            # Desnormalizamos para poder visualizar correctamente
            img_array = tensor_img.permute(1, 2, 0).numpy()
            # Asegurarse de usar IMAGENET_STD y IMAGENET_MEAN definidos globalmente (o pasarlos como argumento)
            img_array = img_array * IMAGENET_STD + IMAGENET_MEAN
            img_array = np.clip(img_array, 0, 1)

            # Graficamos en la celda correspondiente de la grilla
            ax = axs[row, col]
            ax.imshow(img_array)

            if col == 0:
                ax.set_title(f"Original/Var 1 (Img {row+1})", fontsize=10, fontweight='bold')
            else:
                ax.set_title(f"Variación {col+1}", fontsize=10)

            ax.axis('off')

    plt.tight_layout()
    plt.show()

# Ejecución de la función modificada
# Ahora pasamos el train_dataset directamente y el train_transforms ya definido
mostrar_aumentaciones(train_dataset, train_transforms, num_imagenes=4, num_variaciones=3)

"""Celda 6: Bloque de Verificación Final del Batch (Control de Calidad)"""

import matplotlib.pyplot as plt
import numpy as np

# 1. Extraer un único batch real del DataLoader de entrenamiento
images_batch, labels_batch = next(iter(train_loader))

# 2. Reporte de dimensiones y rangos exigidos por la cátedra
print("═" * 60)
print("             VERIFICACIÓN TÉCNICA DEL BATCH")
print("═" * 60)
print(f"Forma del tensor de imágenes (B, C, H, W) : {images_batch.shape}")
print(f"Forma del tensor de etiquetas (B,)         : {labels_batch.shape}")
print(f"Rango de valores en el lote (Mínimo)       : {images_batch.min().item():.4f}")
print(f"Rango de valores en el lote (Máximo)       : {images_batch.max().item():.4f}")
print("═" * 60)

# 3. Graficar un subconjunto de 8 imágenes desnormalizadas para el reporte visual
plt.figure(figsize=(16, 8))
for idx in range(8):
    img_tensor = images_batch[idx]
    label_idx = labels_batch[idx].item()

    # Pasar de (C, H, W) a (H, W, C) y desnormalizar
    img_np = img_tensor.permute(1, 2, 0).numpy()
    img_np = img_np * IMAGENET_STD + IMAGENET_MEAN
    img_np = np.clip(img_np, 0, 1)

    plt.subplot(2, 4, idx + 1)
    plt.imshow(img_np)
    plt.title(f"Contenedor Destino:\n{CONTENEDORES_NAMES[label_idx]}", fontsize=10, fontweight='bold')
    plt.axis('off')

plt.tight_layout()
plt.show()

"""Para dar cumplimiento a los requerimientos de la tercera semana del pliego del proyecto, avanzamos en la fase de modelado experimental utilizando técnicas de Transferencia de Conocimiento (Transfer Learning).

Tras analizar las alternativas típicas del estado del arte (como ResNet-34 o MobileNetV3), nuestro equipo seleccionó EfficientNet-B0 como el backbone extractor de características principales por los siguientes motivos de ingeniería:

Escalamiento Compuesto (Compound Scaling): A diferencia de las redes tradicionales que escalan de forma aislada una única dimensión del modelo (la profundidad en ResNet, el ancho de canales en WideResNet o la resolución espacial), EfficientNet introduce un método de escalado armónico. Mediante un coeficiente compuesto fijo, escala de forma uniforme la profundidad de capas, el ancho de canales y la resolución de la imagen de entrada. Esto maximiza la captura de características geométricas complejas y texturas con una inversión computacional mínima.

Economía de Parámetros y Mitigación del Overfitting: EfficientNet-B0 cuenta con apenas 5.3 millones de parámetros, logrando una precisión en el dataset ImageNet superior a la de ResNet-50, la cual arrastra más de 25 millones de parámetros. Al tener un dataset compacto (~2.500 imágenes limpias), utilizar un modelo pesado incrementaría drásticamente el riesgo de sobreajuste (overfitting). La esbelteca de EfficientNet actúa como un regularizador implícito.

Viabilidad para Despliegue en Streamlit Cloud (Semana 4): Dado que el modelo final operará en un servidor web gratuito con severas restricciones de memoria RAM y CPU, el peso del archivo de pesos (.pth) y la latencia de inferencia en milisegundos son variables críticas. EfficientNet-B0 garantiza ejecuciones ultra rápidas en entornos embebidos o servidores de baja capacidad, permitiendo que la demo de la cámara web funcione de manera fluida y en tiempo real.

Definición de la Arquitectura y Reemplazo del Clasificador

En esta celda importamos el modelo preentrenado con los pesos oficiales de ImageNet v1, "serruchamos" la cabeza de clasificación original de 1.000 clases y la reemplazamos por una estructura lineal adaptada a nuestros 4 contenedores GIRSU.
"""

import torch
import torch.nn as nn
import torchvision.models as models
from torchvision.models import EfficientNet_B0_Weights

def inicializar_modelo_efficientnet(num_clases=4, entrenar_completo=True):
    """
    Instancia EfficientNet-B0.
    Reemplaza el clasificador final para adaptarlo a la Ley GIRSU Mendoza.
    """
    # 1. Cargar los pesos preentrenados oficiales (ImageNet)
    weights = EfficientNet_B0_Weights.DEFAULT
    model = models.efficientnet_b0(weights=weights)

    # 2. Estrategia de congelamiento (Freezing) para experimentos
    if not entrenar_completo:
        # Modo Feature Extractor: Congelamos todo el backbone
        for param in model.parameters():
            param.requires_grad = False
        print("-> Configuración: Feature Extractor (Backbone Congelado)")
    else:
        # Modo Fine-Tuning End-to-End: Dejamos las capas abiertas a cambios leves
        for param in model.parameters():
            param.requires_grad = True
        print("-> Configuración: Fine-Tuning End-to-End (Backbone Desbloqueado)")

    # 3. Modificar la cabeza del clasificador (Classifier Head)
    # En EfficientNet, el clasificador está dentro de model.classifier en la capa indexada [1]
    in_features = model.classifier[1].in_features

    # Reemplazamos por una capa lineal con salida adaptada a nuestras 4 clases
    model.classifier[1] = nn.Linear(in_features=in_features, out_features=num_clases)

    return model

# Prueba rápida de instanciación
model_test = inicializar_modelo_efficientnet(num_clases=4, entrenar_completo=True)

"""Pérdida Ponderada para Desbalance Urbano e Instanciación

Para evitar que el modelo ignore las clases con menos imágenes (como el tacho Amarillo o el tacho Marrón), calculamos el peso inverso de las clases basándonos en tu set de entrenamiento real de la semana pasada, y configuramos el optimizador AdamW con una tasa de aprendizaje conservadora ($1 \times 10^{-4}$) para evitar la destrucción del conocimiento previo (catastrophic forgetting).
"""

import pandas as pd
import torch.optim as optim

# 1. Detectar hardware (Aprovechar la GPU T4 de Colab)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Entrenando en el dispositivo: {device}")

# 2. Leer el CSV de entrenamiento para calcular el desbalance real de tus carpetas
train_df = pd.read_csv("data/train.csv")
conteo_clases = train_df['label'].value_counts().sort_index().values
total_muestras = len(train_df)

# Calcular pesos usando la inversa de la frecuencia para balancear el gradiente
pesos_clases = total_muestras / (len(conteo_clases) * conteo_clases)
pesos_tensor = torch.FloatTensor(pesos_clases).to(device)

print(f"Conteo de muestras por tacho en Train: {conteo_clases}")
print(f"Pesos calculados aplicados a la función de pérdida: {pesos_clases}")

# 3. Instanciar el modelo definitivo en la GPU
model = inicializar_modelo_efficientnet(num_clases=4, entrenar_completo=True)
model = model.to(device)

# 4. Definir criterio de pérdida ponderada y optimizador con Weight Decay
criterion = nn.CrossEntropyLoss(weight=pesos_tensor)
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)

"""Definición de las Funciones de Entrenamiento y Validación

Para cumplir con la rigurosidad metodológica que exige la cátedra, encapsulamos las rutinas de propagación hacia adelante, cálculo de métricas y retropropagación en funciones independientes por época, utilizando tqdm para seguir de forma visual el progreso del bucle.
"""

from tqdm import tqdm

def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    for images, labels in tqdm(dataloader, desc="🏋️ Entrenando", leave=False):
        images, labels = images.to(device), labels.to(device)

        # Resetear gradientes acumulados
        optimizer.zero_grad()

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass y actualización de pesos
        loss.backward()
        optimizer.step()

        # Estadísticas
        running_loss += loss.item() * images.size(0)
        _, preds = torch.max(outputs, 1)
        correct_predictions += torch.sum(preds == labels.data)
        total_samples += images.size(0)

    epoch_loss = running_loss / total_samples
    epoch_acc = correct_predictions.double() / total_samples
    return epoch_loss, epoch_acc.item()

def validate_one_epoch(model, dataloader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    # Desactivar el cálculo de gradientes para ahorrar memoria y acelerar
    with torch.no_grad():
        for images, labels in tqdm(dataloader, desc="🧪 Validando", leave=False):
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, preds = torch.max(outputs, 1)
            correct_predictions += torch.sum(preds == labels.data)
            total_samples += images.size(0)

    epoch_loss = running_loss / total_samples
    epoch_acc = correct_predictions.double() / total_samples
    return epoch_loss, epoch_acc.item()

"""Bucle de Entrenamiento Principal y Almacenamiento del Modelo

Esta celda ejecuta el entrenamiento durante 10 épocas (tiempo óptimo para EfficientNet con 2.500 imágenes en Colab), monitorea la evolución de las métricas y exporta el archivo binario de pesos .pth directo a tu carpeta de producción para dejar todo listo para el deploy en la Semana 4.
"""

import time

EPOCHS = 10
history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}
best_val_acc = 0.0

print("🚀 Iniciando el proceso de optimización del clasificador...")
start_time = time.time()

for epoch in range(EPOCHS):
    # Entrenar y validar
    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
    val_loss, val_acc = validate_one_epoch(model, val_loader, criterion, device)

    # Guardar métricas en el historial
    history["train_loss"].append(train_loss)
    history["train_acc"].append(train_acc)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)

    print(f"Época [{epoch+1}/{EPOCHS}] -> "
          f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc*100:.2f}% || "
          f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc*100:.2f}%")

    # Guardar los mejores pesos si mejora la precisión en validación
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        os.makedirs("prod", exist_ok=True)
        torch.save(model.state_dict(), "prod/efficientnet_girsu_mendoza.pth")
        print("💾 Se guardaron nuevos pesos óptimos en 'prod/efficientnet_girsu_mendoza.pth'")

total_time = time.time() - start_time
print(f"\n🎉 Entrenamiento completado en {total_time/60:.2f} minutos.")
print(f"🏆 Máxima precisión alcanzada en Validación: {best_val_acc*100:.2f}%")

"""Generación de Gráficas Analíticas (Loss y Accuracy Curves)

Graficamos las curvas de rendimiento para adjuntar al informe escrito, lo que permite evaluar visualmente si el modelo convergió de forma estable o si presenta signos de sobreajuste.
"""

import matplotlib.pyplot as plt

epochs_range = range(1, EPOCHS + 1)

plt.figure(figsize=(14, 5))

# Gráfica de Pérdida (Loss)
plt.subplot(1, 2, 1)
plt.plot(epochs_range, history["train_loss"], label="Train Loss", color="#1f77b4", marker='o')
plt.plot(epochs_range, history["val_loss"], label="Val Loss", color="#ff7f0e", marker='o')
plt.title("Evolución de la Función de Pérdida (CrossEntropy)")
plt.xlabel("Épocas")
plt.ylabel("Pérdida")
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()

# Gráfica de Precisión (Accuracy)
plt.subplot(1, 2, 2)
plt.plot(epochs_range, [acc * 100 for acc in history["train_acc"]], label="Train Acc", color="#2ca02c", marker='o')
plt.plot(epochs_range, [acc * 100 for acc in history["val_acc"]], label="Val Acc", color="#d62728", marker='o')
plt.title("Evolución de la Precisión Global (Accuracy)")
plt.xlabel("Épocas")
plt.ylabel("Precisión (%)")
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()

plt.tight_layout()
plt.show()